import type {NextPage} from 'next'
import Head from 'next/head'
import {KommuneCombobox} from "../components/kommune-combobox";
import {KommuneName} from "../types";
import {useState} from "react";
import {KommuneOverview} from "../components/kommune-overview";
import {useAllEvents, useKommuneEvents} from "../queries";
import {KommuneEventList} from "../components/kommune-event-list";

const Home: NextPage = () => {
    const [kommune, setKommune] = useState<KommuneName | undefined>(undefined);

    const globalEvents = useKommuneEvents("Aarhus"); // TODO change to "landsdækkende"
    const allEvents = useAllEvents()?.slice(0, 10);


    let content;
    if (kommune === undefined) {
        content = null;
    } else {
        content = <KommuneOverview name={kommune}>

        </KommuneOverview>
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <>
                    <div>
                        <h1>Kommende landsdækkende begivenheder</h1>
                        {globalEvents && <KommuneEventList events={globalEvents}/>}
                    </div>

                    <div>
                        <h1>Kommende begivenheder i alle kommuner</h1>
                        {allEvents && <KommuneEventList events={allEvents} endRow={<tr>
                            <td colSpan={999} className={"text-center"}>Og mange flere...</td>
                        </tr>}/>}
                    </div>

                    <div>
                        <h1>Se events og lokalgrupper i din kommune</h1>
                        <KommuneCombobox value={kommune} onChange={setKommune} instanceId={"sdfsfsd"}/>
                    </div>
                </>

                {content}
            </main>

        </div>
    )
}

export default Home
