name: build-docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: rg.nl-ams.scw.cloud/mycoolregistry123
          username: nologin
          password: ${{ secrets.SCW_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rg.nl-ams.scw.cloud/mycoolregistry123/app:latest
          cache-from: type=registry,ref=funcscwklimabevaegelsenssq3zxqs/app:latest
          cache-to: type=inline
